### ISSUE TITLE
Some questions about demo/runtime_demo.py

### ISSUE THREAD

**Issue by zdyshine** [eduardzamfir/NTIRE23-Real-Time-SR#3]
The 66 lines, the input size of the calculation time consumption: input_data = (1, 3, args.crop_size[0], args.crop_size[1]), the default crop_size is [1020,540]. Upsampling twice the resolution is [2040,1080], not the standard 4K. Competition questions require 1080 to 4K. If I rely on the network time-consuming to design a new structure, how much should the crop_size be set to calculate the time-consuming, [1920,1080] or [1020,540]?

**Comment by eduardzamfir** [comment]
The current state of the code is comparable to the validation set we provided during the development phase of the challenge. 
Yes, you are right, the challenge addresses 4K super resolution. However, the provided validation set is based on DIV2K which doesn't provide 4K GT. We provided the demo code to be in line with the current validation set. 
Later during the testing phase of the challenge we will evaluate runtime for 4K upsampling. The test set GT are of size [3840, 2160] and we will provide X2 and X3 downscaled versions.
