### ISSUE TITLE
Is it possible to open online speed test server ，cause we have RTX3090 or similar GPU

### ISSUE THREAD

**Issue by yugaocheng** [eduardzamfir/NTIRE23-Real-Time-SR#4]
Sorry.. I originally understood that it will open online test server like MAI2022 by mistake. However, I have not yet reached the entrance, It is though Codalab?

**Comment by eduardzamfir** [comment]
Hi,
you can find all information about the challenge on CodaLab (https://codalab.lisn.upsaclay.fr/competitions/10227) and in the Readme of this repository.
